import Config from 'react-native-config';
export const ENVConfig = {
  API_URL: Config.API_URL,
  APP_ENV: Config.APP_ENV,
  APP_DISPLAY_NAME: Config.APP_DISPLAY_NAME,
  APP_PLACEHOLDER_NAME: Config.APP_PLACEHOLDER_NAME,
  VERSION_CODE: Config.VERSION_CODE,
  VERSION_NAME: Config.VERSION_NAME,
  BUNDLE_IDENTIFIER: Config.BUNDLE_IDENTIFIER,
 
};